# Generated by Django 3.1.1 on 2020-10-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='term_choices',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=6),
        ),
    ]
