# Generated by Django 3.1.1 on 2020-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story3', '0002_semester_term_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=9),
        ),
    ]
