# Generated by Django 3.1.1 on 2020-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story3', '0003_auto_20201013_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='deskripsi',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
